const SampleData = [
    {
        id:1,
        itemCode:"Aa12",
        itemName:"abc",
        quantity:5,
        price:100,
    },
    {
        id:2,
        itemCode:"SB53",
        itemName:"dfhd",
        quantity:15,
        price:198,
    },
    {
        id:3,
        itemCode:"GH94",
        itemName:"thrth",
        quantity:57,
        price:1840,
    },
    {
        id:4,
        itemCode:"VR421",
        itemName:"yjds",
        quantity:95,
        price:1075,
    }
]
export default SampleData;